//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfullWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizUserStatistic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuizUserStatistic()
        {
            this.SelectedAnswers = new HashSet<SelectedAnswer>();
        }
    
        public long QuizUserStatisticID { get; set; }
        public int correctPercentage { get; set; }
        public long QuizID { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual Quiz Quiz { get; set; }
        public virtual Userr Userr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectedAnswer> SelectedAnswers { get; set; }
    }
}
