//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfullWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectedAnswer
    {
        public long SelectedAnswerID { get; set; }
        public string IsSelectedCorrect { get; set; }
        public long QuestionID { get; set; }
        public Nullable<long> QuizUserStatisticID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual QuizUserStatistic QuizUserStatistic { get; set; }
    }
}
