//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfullWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public Answer()
        {
            
        }
        public long AnswerID { get; set; }
        public string Answer1 { get; set; }
        public string IsCorrect { get; set; }
        public long QuestionID { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
