//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfullWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public Rating()
        {
            
        }
        public long RatingID { get; set; }
        public int Rating1 { get; set; }
        public string Reason { get; set; }
        public long QuizID { get; set; }
    
        public virtual Quiz Quiz { get; set; }
    }
}
